var eventos = {
		"DERI_USUARIO": "01",
		"RAZAO_PERDAROUBO": "01",
		"RAZAO_SOLIC_ATENDENTE": "02",
		"RAZAO_SMENU_DESBLOQUEIO": "02",
		"DERI_SISTEMA": "02",
		"RAZAO_EXCTENT_CARTAO": "04",
		"RAZAO_EXCTENT_OPCAO": "05",
		"RAZAO_TIMEOUT_HOST": "08",
		"RAZAO_EXCTENT_CPF": "04",
		"RAZAO_EXCTENT_DTNASC": "04",
		"RAZAO_CDBLOQM_UR 80": "06",
		"RAZAO_COD_DIFERE_UR_50": "07",
		"RAZAO_COD_DIFERE_UR_80": "07",
		"RAZAO_COD_DIFERE_UR_55": "07",
		"RAZAO_COD_DIFERE_UR_60": "07",
		"RAZAO_COD_DIFERE_UR_85": "07",
		"RAZAO_COD_DIFERE_UR_87": "07",
		"RAZAO_COD_DIFERE_UR_88": "07",
		"RAZAO_COD_DIFERE_UR_90": "07",
		"RAZAO_RC_570_UR_50": "07",
		"RAZAO_RC_580_UR_50": "07",
		"RAZAO_MOTIVO_000_CONSULTA_EXECUTADA_COM_SUCESSO": "01",
		"RAZAO_MOTIVO_401_CARTAO_NAO_ENCONTRADO": "02",
		"RAZAO_MOTIVO_405_ERRO_DE_BANCO_DE_DADOS": "03",
		"RAZAO_MOTIVO_406_CLIENTE_NAO_ENCONTRADO": "04",
		"RAZAO_MOTIVO_407_EXTRATO_NAO_ENCONTRADO": "05",
		"RAZAO_MOTIVO_408_INCONSISTENCIA_DE_DADOS": "06",
		"RAZAO_MOTIVO_409_CARTAO_JA_DESBLOQUEADO": "07",
		"RAZAO_MOTIVO_410_CARTAO_NAO_ESTA_ATIVO": "08",
		"RAZAO_MOTIVO_411_CPF DO_DEPENDENTE": "09",
		"RAZAO_MOTIVO_412_CARTAO_DO_DEPENDENTE": "10",
		"RAZAO_MOTIVO_413_CLIENTE_NAO_HABILITADO": "11",
		"RAZAO_MOTIVO_414_LIQUIDACAO_EM_ANDAMENTO": "12",
		"RAZAO_MOTIVO_415_ACORDO_EM_ANDAMENTO": "13",
		"RAZAO_MOTIVO_416_FINANCIAMENTO_QUESTIONADO": "14",
		"RAZAO_MOTIVO_417_DATA_INVALIDA": "15",
		"RAZAO_MOTIVO_418_EXTRATO_TEMPORARIAMENTO_PAGO": "16",
		"RAZAO_OUTROS": "99",
		"RAZAO_COBRANCA": "00"
}



function getEventosDerivacao(nome) {
	var nomeEvento = eventos[nome];
	if (nomeEvento == undefined || nomeEvento == ''){
		nomeEvento = '  ';
	}

	return (nomeEvento);
}