var eventos = {
	//Tickt
		"TICK_LIMIT" : "LIMIT",
		"TICK_FIN" : "FIN",
		"TICK_BSY" : "BSY",
		"TICK_TRANSF" : "TRANSF",
		"TICK_CALLBK" : "CALLBK",
		"TICK_BLKLST" : "BLKLST",
		"TICK_IDPOS" : "IDPOS",
		"TICK_CICS" : "CICS",
		"TICK_TST" : "TST",
		"TICK_CAP" : "CAP",
		"TICK_SEG" : "SEG",
		"TICK_PRO" : "PRO",
		"TICK_FAX" : "FAX",
		"TICK_M1" : "M1",
		"TICK_M2" : "M2",
		"TICK_M3" : "M3",
		"TICK_M4" : "M4",
		"TICK_M5" : "M5",
		"TICK_M6" : "M6",
		"TICK_M7" : "M7",
		"TICK_M8" : "M8",
		"TICK_M9" : "M9",
		"TICK_M10" : "M10",
		"TICK_M11" : "M11",
		"TICK_M12" : "M12",
		"TICK_M13" : "M13",
		"TICK_M14" : "M14",
		"TICK_M15" : "M15",
		"TICK_M16" : "M16",
		"TICK_M17" : "M17",
		"TICK_M18" : "M18",
		"TICK_M19" : "M19",
		"TICK_M20" : "M20",
		"TICK_M21" : "M21",
		"TICK_M22" : "M22",
		"TICK_M23" : "M23",
		"TICK_M24" : "M24",
		"TICK_M25" : "M25",
		"TICK_M26" : "M26",
		"TICK_M27" : "M27",
		"TICK_M28" : "M28",
		"TICK_M29" : "M29",
		"TICK_M30" : "M30",
		"TICK_M31" : "M31",
		"TICK_M32" : "M32",
		"TICK_M33" : "M33",
		"TICK_M34" : "M34",
		"TICK_M35" : "M35",
		"TICK_M36" : "M36",
		"TICK_M37" : "M37",
		"TICK_M38" : "M38",
		"TICK_M39" : "M39",
		"TICK_M40" : "M40",
		"TICK_M41" : "M41",
		"TICK_M42" : "M42",
		"TICK_M43" : "M43",
		"TICK_M44" : "M44",
		"TICK_M45" : "M45",
		"TICK_M46" : "M46"  ,
		"TICK_M47" : "M47"  ,
		"TICK_M48" : "M48"  ,
		"TICK_VCRI" : "VCRI",
		"TICK_VI" : "VI",
		"TICK_VDFATND" : "VDFATND",
		"TICK_VLM" : "VLM",
		"TICK_VNC" : "VNC",
		"TICK_VCD" : "VCD",
		"TICK_VSI" : "VSI",
		"TICK_VFD" : "VFD",
		"TICK_VCB" : "VCB",
		"TICK_VPF" : "VPF",
		"TICK_VSD" : "VSD",
		"TICK_VTC" : "VTC",
		"TICK_VND" : "VND",
		"TICK_VSS" : "VSS",
		"TICK_VEX" : "VEX",
		"TICK_VSM" : "VSM",
		"TICK_VAF" : "VAF",
		"TICK_VTL" : "VTL",
		"TICK_VAGS" : "VAGS",
		"TICK_VMD" : "VMD"  ,
		"TICK_VCS" : "VCS",
		"TICK_VLA" : "VLA",
		"TICK_VPIF" : "VPIF",
		"TICK_VIF" : "VIF",
		"TICK_VNG" : "VNG",
		"TICK_VNP" : "VNP",
		"TICK_VEP" : "VEP",
		"TICK_VPT" : "VPT",
		"TICK_NCvv" : "NCVV",
		"TICK_NSnhAE" : "NSnhAE",
		"TICK_NCARTAO" : "NCARTAO",
		"TICK_NCPF" : "NCPF",
		"TICK_NCNPJ" : "NCNPJ",
		"TICK_NSnAt" : "NSnAt",
		"TICK_NSnNv" : "NSnNv",
		"TICK_NSnCf" : "NSnCf",
		"TICK_NDtPgto" : "NDtPgto"  ,
		"TICK_NP1" : "NP1",
		"TICK_NP2" : "NP2",
		"TICK_NP3" : "NP3",
		"TICK_NP4" : "NP4",
		"TICK_NP5" : "NP5",
		"TICK_NP6" : "NP6",
		"TICK_NP7" : "NP7",
		"TICK_NP8" : "NP8",
		"TICK_NP9" : "NP9",
		"TICK_NP10" : "NP10",
		"TICK_NP11" : "NP11",
		"TICK_NP12" : "NP12",
		"TICK_NP13" : "NP13",
		"TICK_NP14" : "NP14",
		"TICK_NP15" : "NP15",
		"TICK_NP16" : "NP16",
		"TICK_NP17" : "NP17",
		"TICK_CARDADD" : "CARDADD",
		"TICK_LOG_MN1" : "P1",
		"TICK_LOG_MHLMAKRO" : "P2",
		"TICK_LOG_MPR" : "P3",
		"TICK_LOG_MBLOQPR" : "P4",
		"TICK_LOG_MTPBLOQ" : "P5",
		"TICK_LOG_MOPCARBLOQ" : "P6",
		"TICK_LOG_MCONFPR" : "P7",
		"TICK_LOG_MADICTIT" : "P8",
		"TICK_LOG_MPOSBLOQPR" : "P9",
		"TICK_LOG_MCONTESTACAD" : "P10",
		"TICK_LOG_MNC" : "P11",
		"TICK_LOG_MPOSPROP" : "P12",
		"TICK_LOG_COLCPFCNPJ" : "P13",
		"TICK_LOG_MDESBLOQ" : "P14",
		"TICK_LOG_COLCARADIC" : "P15",
		"TICK_LOG_MCPFNCARTAO" : "P16",
		"TICK_LOG_MN2" : "P17",
		"TICK_LOG_MHLCEA" : "P18",
		"TICK_LOG_MALTERARCEL" : "P19",
		"TICK_LOG_MCADASTRARCEL" : "P20",
		"TICK_LOG_COLDDDCEL" : "P21",
		"TICK_LOG_MCONFCADCEL" : "P22",
		"TICK_LOG_COLSENHAATUAL_VALID" : "P23",
		"TICK_LOG_COLPIDCPFCNPJ" : "P24",
		"TICK_LOG_COLPIDDIANASC" : "P25",
		"TICK_LOG_COLPIDMESNASC" : "P26",
		"TICK_LOG_COLPIDANONASC" : "P27",
		"TICK_LOG_COLPIDVENCFAT" : "P28",
		"TICK_LOG_COLPIDVALIDADECAR" : "P29",
		"TICK_LOG_COLPIDCVVCVC" : "P30",
		"TICK_LOG_COLPIDTEMADICIONAL" : "P31",
		"TICK_LOG_COLPIDTEMPROTPR" : "P32",
		"TICK_LOG_MVENDAS" : "P33",
		"TICK_LOG_MCANCVENDAS" : "P34",
		"TICK_LOG_MPOSLIM" : "P35",
		"TICK_LOG_MFATPARCPAGTO" : "P36",
		"TICK_LOG_MPARC" : "P37",
		"TICK_LOG_MSENHAATIVA" : "P38",
		"TICK_LOG_COLSENHAATUAL" : "P39",
		"TICK_LOG_COLSENHANOVA" : "P40",
		"TICK_LOG_COLCONFSENHANOVA" : "P41",
		"TICK_LOG_MCONFALTCADSENHA" : "P42",
		"TICK_LOG_MCONFALTEND" : "P43",
		"TICK_LOG_MOUTRASSOLIC" : "P44",
		"TICK_LOG_MPGMFIDEL" : "P45",
		"TICK_LOG_MCONTCANC" : "P46",
		"TICK_LOG_MMOTIVOCANC" : "P47",
		"TICK_LOG_MCONTESTACOMPRASAQUE" : "P48",
		"TICK_LOG_MATRASO" : "P49"       ,
		"TICK_LOG_MCONTPARC" : "P50"     ,
		"TICK_LOG_MPOSFATURA" : "P51"    ,
		"TICK_LOG_MCVV" : "P52"          ,
		"TICK_LOG_PEDECVV" : "P53"       ,
		"TICK_LOG_MOPPAR" : "P54"        ,
		"TICK_LOG_MCONTOPPAR" : "P55"    ,
		"TICK_LOG_MCONDESNEG" : "P56"    ,
		"TICK_LOG_MAPPIB" : "P57"  
}



function getEventosTickLabel(nome) {
	var nomeEvento = eventos[nome];
	if (nomeEvento == undefined || nomeEvento == '') {
		if(nome.substring(0,9) =='TICK_LOG_'){
			nomeEvento = nome.substring(9);
		}else{
			nomeEvento = nome.substring(5);
		}	
	}
	return (removerAcentos(nomeEvento)).substring(0, 64);
}

/**
 * Remove acentos de strings
 * @param  {String} string acentuada
 * @return {String} string sem acento
 */
var map = { "â": "a", "Â": "A", "à": "a", "À": "A", "á": "a", "Á": "A", "ã": "a", "Ã": "A", "ê": "e", "Ê": "E", "è": "e", "È": "E", "é": "e", "É": "E", "î": "i", "Î": "I", "ì": "i", "Ì": "I", "í": "i", "Í": "I", "õ": "o", "Õ": "O", "ô": "o", "Ô": "O", "ò": "o", "Ò": "O", "ó": "o", "Ó": "O", "ü": "u", "Ü": "U", "û": "u", "Û": "U", "ú": "u", "Ú": "U", "ù": "u", "Ù": "U", "ç": "c", "Ç": "C" };
function removerAcentos(s) { return s.replace(/[\W\[\] ]/g, function (a) { return map[a] || a }).replace(" - ", "-").replace(" – ", "-").replace(" – ", "-").replace(/\s/g, "_") };
	
	